---
Prefix: §a§lFFA§r §8| §f
Armor:
- iron_helmet
- iron_chestplate
- iron_leggings
- iron_boots
Items:
- - iron_sword
  - 1
- - golden_apple
  - 3
JoinMessage: §e{PLAYER}§a joined the game.
LeaveMessage: §e{PLAYER}§c left the game.
KillMessage: §aYou killed §c{VICTIM}§a!
KilledMessage: '§cYou were killed by §e{KILLER} §6[{LAST_HEALTH}]§c! '
DeathMessage: §cYou died!
Title: §l§aFFA
Subtitle: §eWelcome to the game!
SpawnRadius: 4
ProtectionMessage: You're too close to the spawn to fight with other players.
...
