name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.3
  
    - name: composer-installer-action
      uses: nanasess/composer-installer-action@v2.0.0


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
